### ISSUE TITLE
Add details about this repository in the 'package.json' file

### ISSUE THREAD

**Issue by vipranarayan14** [alirezamirian/use-dropbox-chooser#4]
I found [this](https://www.npmjs.com/package/use-dropbox-chooser) package in npm. I wanted to know more about it such as code, implementation, etc. But I could not find the link to this repository. Then I had to search GitHub for this repository.

To avoid such inconveniences for other developers using your package in future and to make your repository easy to discover, please add details about the same in the 'package.json'. The details can be like:

```json
  "keywords": [
    "dropbox",
	"chooser"
  ],
  "repository": {
    "type": "git",
    "url": "git+https://github.com/alirezamirian/use-dropbox-chooser.git"
  },
  "bugs": {
    "url": "https://github.com/alirezamirian/use-dropbox-chooser/issues"
  }
```

**Comment by alirezamirian** [comment]
Thanks. Fixed.

**Comment by vipranarayan14** [comment]
Thanks. 

And thanks for the `DropboxAppProvider` example. I saw it in code but didn't know how to use it.
